Genre.create(name:'メンズ')
Genre.create(name:'レディース')
Genre.create(name:'キッズ')
Item.create(name:'シャツ', status_id:'1', price:'1800', genre_id:'1')
Item.create(name:'シャツ', status_id:'1', price:'2000', genre_id:'2')
Item.create(name:'シャツ', status_id:'4', price:'1000', genre_id:'3')
Item.create(name:'シャツ', status_id:'4', price:'1500', genre_id:'1')
Item.create(name:'シャツ', status_id:'6', price:'500', genre_id:'2')
Item.create(name:'シャツ', status_id:'6', price:'800', genre_id:'3')
Item.create(name:'パーカー', status_id:'1', price:'3200', genre_id:'1')
Item.create(name:'パーカー', status_id:'1', price:'3500', genre_id:'2')
Item.create(name:'パーカー', status_id:'4', price:'2500', genre_id:'3')
Item.create(name:'パーカー', status_id:'4', price:'2000', genre_id:'1')
Item.create(name:'パーカー', status_id:'6', price:'900', genre_id:'2')
Item.create(name:'パーカー', status_id:'6', price:'1000', genre_id:'3')
Item.create(name:'スカート', status_id:'1', price:'2000', genre_id:'2')
Item.create(name:'スカート', status_id:'1', price:'3500', genre_id:'3')
Item.create(name:'スカート', status_id:'4', price:'800', genre_id:'2')
Item.create(name:'スカート', status_id:'4', price:'1500', genre_id:'3')
Item.create(name:'スカート', status_id:'6', price:'300', genre_id:'2')
Item.create(name:'スカート', status_id:'6', price:'500', genre_id:'3')
Item.create(name:'ボトムス', status_id:'1', price:'3000', genre_id:'1')
Item.create(name:'ボトムス', status_id:'1', price:'4000', genre_id:'2')
Item.create(name:'ボトムス', status_id:'4', price:'1800', genre_id:'3')
Item.create(name:'ボトムス', status_id:'4', price:'1500', genre_id:'1')
Item.create(name:'ボトムス', status_id:'6', price:'800', genre_id:'2')
Item.create(name:'ボトムス', status_id:'6', price:'1000', genre_id:'3')